/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unity;

import dao.DBConnect;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Random;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.HOADONNHAP;
import model.Nhanvien;
import model.Sach;

/**
 *
 * @author huhuh
 */
public class XuatsachAdmin extends javax.swing.JFrame {
    
    private List<Sach> list=new ArrayList<>();
    private List<HOADONNHAP> list1=new ArrayList<>();
    java.util.Date date = Calendar.getInstance().getTime();
    String tmp;
    public void load() {
        ts.removeAllItems();
        tg.removeAllItems();
        ms.removeAllItems();
        tl.removeAllItems();
         try{
                    String sql = "SELECT * FROM SACH";
                    Connection conn=DBConnect.getConnection();
                    PreparedStatement pst=conn.prepareCall(sql);
                    ResultSet rs=pst.executeQuery();

                    while(rs.next()){
                        ms.addItem(rs.getString("MaSach").trim());
                    }
                    
                    sql = "SELECT DISTINCT TenSach FROM SACH";
                    conn=DBConnect.getConnection();
                    pst=conn.prepareCall(sql);
                    rs=pst.executeQuery();
                    
                    while(rs.next()){
                        ts.addItem(rs.getString("TenSach").trim());
                    }
                    sql = "SELECT DISTINCT LoaiSach FROM SACH";
                    conn=DBConnect.getConnection();
                    pst=conn.prepareCall(sql);
                    rs=pst.executeQuery();
                    
                    while(rs.next()){
                        tl.addItem(rs.getString("LoaiSach").trim());
                    }
                    
                    sql = "SELECT DISTINCT TacGia FROM SACH";
                    conn=DBConnect.getConnection();
                    pst=conn.prepareCall(sql);
                    rs=pst.executeQuery();
                    
                    while(rs.next()){
                        tg.addItem(rs.getString("TacGia").trim());
                    }
                    
                }
                catch(Exception ex){
                    ex.printStackTrace();
                }
    }
    /**
     * Creates new form Nhapsach
     */
    public XuatsachAdmin(String abc) {
        initComponents();
        load();
        begin.setText(abc);
       //begin.setVisible(false);
       tmp="mhdx";
            Random generator = new Random();
            for(int i=1;i<=6;i++) {
                int value = generator.nextInt(9) + 1;
                tmp+=value;
            }
     
            
    }
    
    public boolean checkDup() {
        for(int i=0;i<list.size();i++) {
            if(list.get(i).getMaSach()==(String)ms.getSelectedItem())
                return true;
        }
        return false;
    }
    
    public boolean checkDupInDB(String ms) throws SQLException {
        
                String sql = "SELECT * FROM SACH where MaSach=?";
                Connection conn=DBConnect.getConnection();
                PreparedStatement pst=conn.prepareCall(sql);
                pst.setString(1, ms);
                ResultSet rs=pst.executeQuery();

                if(rs.next()){    
                        return true;
                }
            
        return false;
    }
    
    public boolean checkSL(Sach sach) {
        Connection conn = null;
        try{
            String sqlChange="Select * from SACH where MaSach=? ";
            conn=DBConnect.getConnection();
            PreparedStatement pst=conn.prepareCall(sqlChange);
            pst.setString(1, sach.getMaSach());
            ResultSet rs=pst.executeQuery();
            int i = 0;
            while(rs.next()) {
                i=rs.getInt("SoLuong");
                
            }
            
            if(i<sach.getSL())
                return false;
            
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        begin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ms = new javax.swing.JComboBox<>();
        ts = new javax.swing.JComboBox<>();
        tl = new javax.swing.JComboBox<>();
        sl = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tg = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        jButton1.setText("Trang chính");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("XUẤT SÁCH");

        begin.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(433, 433, 433)
                .addComponent(begin)
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(begin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 255, 153));

        jLabel3.setText("Mã Sách");

        jLabel4.setText("Tên Sách");

        jLabel5.setText("Thể loại");

        jLabel6.setText("Số lượng xuất");

        ms.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        ms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msActionPerformed(evt);
            }
        });

        ts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsActionPerformed(evt);
            }
        });

        tl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlActionPerformed(evt);
            }
        });

        jLabel14.setText("Tác giả");

        tg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgActionPerformed(evt);
            }
        });

        jButton6.setText("Thêm sách vào hóa đơn");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(ts, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(ms, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(26, 26, 26)
                                        .addComponent(tg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tl, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(27, 27, 27)
                                        .addComponent(sl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(jButton6)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(ms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        status.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        status.setForeground(new java.awt.Color(255, 51, 51));
        status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status.setText("Trạng thái");

        jButton7.setText("Xem trước hóa đơn");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton3.setText("Xác nhận xuất sách");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(475, 475, 475)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(433, 433, 433))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(426, 426, 426))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(316, 316, 316))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(status)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msActionPerformed
        // TODO add your handling code here:
        ts.removeAllItems();
        tg.removeAllItems();
        tl.removeAllItems();
        sl.setText("");
        try{
            String sqlChange="Select * from SACH where MaSach=? ";
            Connection conn=DBConnect.getConnection();
            PreparedStatement pst=conn.prepareCall(sqlChange);
            pst.setString(1, (String)ms.getSelectedItem());
            ResultSet rs=pst.executeQuery();
            while(rs.next()) {
                tg.addItem(rs.getString("TacGia").trim());
                tl.addItem(rs.getString("LoaiSach").trim());
                ts.addItem(rs.getString("TenSach").trim());

            }
            



        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_msActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(!sl.getText().equals("")) {
            Nhanvien nhanvien=new Nhanvien();
            nhanvien.setInfor(begin.getText());
            if(!list.isEmpty()) {
            for(int i=0;i<list.size();i++) {
                nhanvien.xuatsach(list.get(i));
                SimpleDateFormat formatter1 = new SimpleDateFormat("hh:mm:ss");
                String time=formatter1.format(date);
                java.sql.Time timeValue;
                try {
                    timeValue = new java.sql.Time(formatter1.parse(time).getTime());
                    list1.get(i).setThoiGian(timeValue);
                } catch (ParseException ex) {
                    Logger.getLogger(XuatsachAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                nhanvien.xuathoadonxuat(list1.get(i),tmp);
            }
            
            status.setText("Xuất sách thành công");
            list.clear();
            list1.clear();
            load();

            

            } else status.setText("Chưa thêm sách cần xuất vào hóa đơn");

        } else status.setText("Chưa nhập số lượng!");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tlActionPerformed

    private void tgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tgActionPerformed

    private void tsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminMain f=new AdminMain(this.begin.getText());
        f.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Nhanvien nhanvien=new Nhanvien();
        nhanvien.setInfor(begin.getText());
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        String day = formatter.format(date);
        SimpleDateFormat formatter1 = new SimpleDateFormat("hh:mm:ss");
        String time=formatter1.format(date);
        InhoadonNhapsach hd= new InhoadonNhapsach(list,nhanvien,day,time,tmp);
        
        hd.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:    
            if(sl.getText()=="") {
                Sach sach=new Sach();
            sach.setInfor((String)ms.getSelectedItem());
            sach.setSL(Integer.parseInt(sl.getText()));
            if(checkSL(sach)) {
                list.add(sach);
                HOADONNHAP hdn=new HOADONNHAP();
                hdn.setMaSach((String)ms.getSelectedItem());
                hdn.setMHDN(tmp);
                hdn.setMaNV(begin.getText());
                hdn.setSL(Integer.parseInt(sl.getText()));

                list1.add(hdn);

                status.setText("Thêm vào hóa đơn thành công");
            } else status.setText("Không đủ số lượng sách "+(String)ms.getSelectedItem());
            
        
        

        
        CompletableFuture.delayedExecutor(2, TimeUnit.SECONDS).execute(() -> {
           status.setText("Trạng thái");
        });
            } else {
                status.setText("Hãy nhập số lượng");
            
        
        

        
        CompletableFuture.delayedExecutor(2, TimeUnit.SECONDS).execute(() -> {
           status.setText("Trạng thái");
        });
            }
            
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XuatsachAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XuatsachAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XuatsachAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XuatsachAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String a = null;
                new XuatsachAdmin(a).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel begin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> ms;
    private javax.swing.JTextField sl;
    private javax.swing.JLabel status;
    private javax.swing.JComboBox<String> tg;
    private javax.swing.JComboBox<String> tl;
    private javax.swing.JComboBox<String> ts;
    // End of variables declaration//GEN-END:variables
}
